version: '3.8'

services:
  prediction:
    build:
      context: .
      dockerfile: Dockerfile.service
    ports:
      - "8000:8000"
    environment:
      - AWS_DEFAULT_REGION=eu-west-1
      - S3_BUCKET=ecommerce-ml-pipeline-data
      - MODEL_PATH=/app/models
      - FEATURE_PATH=/app/features
    volumes:
      - ./models:/app/models
      - ./features:/app/features
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  monitoring:
    build:
      context: .
      dockerfile: Dockerfile.monitoring
    ports:
      - "8001:8001"
    environment:
      - AWS_DEFAULT_REGION=eu-west-1
      - S3_BUCKET=ecommerce-ml-pipeline-data
      - METRICS_PATH=/app/metrics
    volumes:
      - ./metrics:/app/metrics
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./infrastructure/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

volumes:
  prometheus_data: {}
