global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prediction_service'
    static_configs:
      - targets: ['prediction:8000']
    metrics_path: '/metrics'

  - job_name: 'monitoring_service'
    static_configs:
      - targets: ['monitoring:8001']
    metrics_path: '/metrics'
