services:
  prediction-service:
    build:
      context: ..
      dockerfile: docker/prediction/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=eu-west-1
      - S3_BUCKET=ecommerce-ml-pipeline-data
      - MODEL_PATH=/app/models
      - FEATURE_PATH=/app/features
      - DEVELOPMENT_MODE=true
      - PRODUCTION_READY=true
      - SKIP_METRICS=false
      - PYTHONPATH=/app
      - ALLOW_PICKLE=true
    volumes:
      - ../models:/app/models
      - ../features:/app/features
    restart: unless-stopped

