global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prediction_service'
    static_configs:
      - targets: ['prediction:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'model_metrics'
    static_configs:
      - targets: ['prediction:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '^model_.*'
        action: keep
